# Usar una imagen de Java 17
FROM openjdk:17-jdk-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar el JAR al contenedor
COPY target/serviciosEscuela-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto (Render lo usa automáticamente)
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["java", "-jar", "app.jar"]